name: Continuous Integration

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}${{ github.event_name == 'workflow_dispatch' && '[dispatch]' || '' }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
  TERM: xterm-color

jobs:
  ci:
    name: "CI"
    uses: ./.github/workflows/continuous-integration.build.yml
    secrets: inherit
  ci-qa:
    name: "CI"
    uses: ./.github/workflows/continuous-integration.build-qa.yml
    secrets: inherit
